{% set name = "pyrolite" %}
{% set version = "0.3.8.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pyrolite-{{ version }}.tar.gz
  sha256: ccfaad9dea81732f75d90004c850b67f948eca9d340afc4c0bb3741acc595ec6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=80
    - setuptools-scm[simple] >=8
  run:
    - python >={{ python_min }}
    - numpy
    - periodictable
    - matplotlib-base >=3.9
    - mpltern >=0.4.0
    - scipy >=1.2
    - sympy >=1.7
    - pandas >=1.0
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyrolite
    - pyrolite.plot

about:
  home: https://github.com/morganjwilliams/pyrolite
  summary: Tools for geochemical data analysis.
  license: MIT
  license_file: LICENSE
  doc_url: https://pyrolite.readthedocs.io/
  dev_url: https://github.com/morganjwilliams/pyrolite

extra:
  recipe-maintainers:
    - morganjwilliams
    - eazzzon
