{% set name = "pyrolite" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrolite-{{ version }}.tar.gz
  sha256: 1c376fa10124670cd7c7966eee2b2ae2c4d3e7248136fd9fc7622e5e762370c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - joblib
    - matplotlib-base >=3.5
    - mpltern >=0.3.4
    - mpmath
    - numpy
    - numpydoc
    - openpyxl
    - pandas >=1.0
    - periodictable
    - psutil
    - requests
    - scipy >=1.2
    - sympy >=1.7
    - tinydb >4.1
    - typing-extensions
    - xlrd

test:
  imports:
    - pyrolite
    - pyrolite.plot

about:
  home: https://github.com/morganjwilliams/pyrolite
  summary: Tools for geochemical data analysis.
  license: LicenseRef-CSIRO-Open-Source
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pyrolite.readthedocs.io/
  dev_url: https://github.com/morganjwilliams/pyrolite

extra:
  recipe-maintainers:
    - morganjwilliams
    - eazzzon
