{% set name = "pyrolite" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrolite-{{ version }}.tar.gz
  sha256: fc17fb6f62a90d6615d9e17fe1fcae8794ae7ddadc10b5460732acc584e1163e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy
    - numpydoc
    - tinydb >4.1
    - periodictable
    - matplotlib-base >=3.5
    - mpltern >=0.4.0
    - scipy >=1.2
    - sympy >=1.7
    - pandas >=1.0
    - requests

test:
  imports:
    - pyrolite
    - pyrolite.plot

about:
  home: https://github.com/morganjwilliams/pyrolite
  summary: Tools for geochemical data analysis.
  license: LicenseRef-CSIRO-Open-Source
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pyrolite.readthedocs.io/
  dev_url: https://github.com/morganjwilliams/pyrolite

extra:
  recipe-maintainers:
    - morganjwilliams
    - eazzzon
